### ISSUE TITLE
Rename repositories for consistency and clarity

### ISSUE THREAD

**Issue by dslmeinte** [ehn-dcc-development/eu-dcc-overview#11]
Rename repositories in the `ehn-dcc-development` organisation for consistency and clarity.

Specific examples:

eu-dcc-overview
eu-dcc-schema
eu-dcc-valuesets
eu-dcc-business-rules
eu-dcc-hcert-spec

The idea is to give every repository's name a prefix `eu-dcc-`.

The existing (old) GitHub URLs are still valid, and will redirect to the new URLs. For info on renaming, see [the GitHub documentation on renaming](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository).

Nevertheless, it's advisable to update the URLs in documentation.

**Comment by dslmeinte** [comment]
@skounis @kruzikh What do you think?
(CC: @ryanbnl )

**Comment by skounis** [comment]
I strongly support consistency. What bothers me, however, not just for these repos, is if we need to use a prefix that links to the organization itself. In this case, the `ehn-` part repeats the, and plays the exact same role as, the name of the organization. 

The official name of the service is EU-DCC (European Union Digital Covid Certificates). With this in mind, I would suggest `eu-dcc-` as an alternative prefix for everything that is officially used by the ecosystem.

**Comment by kruzikh** [comment]
I agree with @skounis. eu-dcc- prefix seems to be more appropriate.

**Comment by dslmeinte** [comment]
Updated description to reflect @skounis 's suggestion.

**Comment by ryanbnl** [comment]
Done!
